### ISSUE TITLE
Website title not being updated

### ISSUE THREAD

**Issue by aravindthokala** [austingebauer/devise#6]
In the config file, even though the website title field is updated with my name, it shows my website link instead of my name.

**Comment by austingebauer** [comment]
Hi, @aravindthokala! 

Can you confirm that your config includes `title = ""` at the top level? The title field should be set appropriately (see https://github.com/austingebauer/devise/blob/master/layouts/partials/head.html#L2). I'm also populating `title = "Austin Gebauer"` for [austingebauer.com](https://austingebauer.com/), for which you can see it has the correct title.

**Comment by aravindthokala** [comment]
Yes, the config.toml has 
title = "Aravind Thokala"

**Comment by austingebauer** [comment]
Hmm, interesting! I'm not able to reproduce where the title is not what's specified in the `title = ""` setting in the config.

For example, my config looks like:
```toml
baseURL = "http://austingebauer.com/"
languageCode = "en-us"
title = "Austin Gebauer"
theme = "devise"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2020, Austin Gebauer"
```

Any additional details you can provide as to why this might be happening?
